version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_DB: jwt_security
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    image: masterbaiter/backend:latest
    container_name: backend-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jwt_security
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - backend-network

  frontend:
    image: masterbaiter/frontend:latest
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
