version: '3.8'

services:
  # PostgreSQL container
  postgres:
    image: postgres:latest
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_DB: jwt_security
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Spring Boot App container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jwt_security
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - backend-network

  # React Frontend container
  frontend:
    build:
      context: ./frontend  # Path to your React app
      dockerfile: Dockerfile  # Make sure this exists at ./frontend/Dockerfile
    container_name: frontend-app
    ports:
      - "3000:80"  # nginx exposes on port 80 inside container
    depends_on:
      - backend
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
